server:
    port: 8081
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/javapro06
        username: postgres
        password: "1234"
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                format_sql: true
    flyway:
        validate-on-migrate: true
        sql-migration-prefix: v

