server:
    port: 8081
spring:
    datasource:
#    если используется docker, то вместо localhost должно быть указано имя сервиса как в docker-compose.yml !!! в данном случае db
#    url: jdbc:postgresql://db:5432/javapro06
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/javapro06
        username: postgres
        password: "1234"
